name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main  
      - maint/12
  pull_request:
    branches:
      - main
      - maint/12

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Install dependencies and run tests
    - name: Build and test
      run: mvn clean verify
